USE [master]
GO
CREATE LOGIN [sede] WITH PASSWORD=N'sede.', DEFAULT_DATABASE=[sede], DEFAULT_LANGUAGE=[Português], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [sede]
GO
CREATE USER [sede] FOR LOGIN [sede]
GO
